#!/usr/bin/env node
// scripts/emit-mirror.mjs
//
// Generates the consumer-side mirror table from manifest.json.
//
//   node scripts/emit-mirror.mjs                       # every known consumer
//   node scripts/emit-mirror.mjs --consumer home-flix  # just one
//   node scripts/emit-mirror.mjs --check               # fail if any file is stale
//
// The table is generated rather than hand-written because a mirror URL without
// its checksum is just another unverified download, and hand-copying 16 hashes
// into two repositories is exactly the kind of duplication that drifts silently:
// a wrong hash does not break the build, it makes the mirror get skipped and the
// project quietly falls back to the upstream host this repository exists to
// stop depending on.
//
// Re-run after every `npm run publish` and commit the result in each consumer.

import { existsSync, readFileSync, writeFileSync } from 'fs'
import { join, resolve } from 'path'
import { fileURLToPath } from 'url'

import { REPO_SLUG } from '../sidecars.config.mjs'
import { readManifest } from './lib/manifest.mjs'
import { logger, parseArgs } from './lib/log.mjs'

const ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), '..')
const log = logger('emit-mirror')

// Where each consumer keeps the generated module, relative to this repository.
// Siblings on purpose: these projects are checked out next to each other, but a
// consumer must never need this repository present at build time — the file is
// committed there and stands alone, which is what makes it work inside a build
// container that only mounts the one project.
const CONSUMERS = {
  'home-flix': '../home-flix/scripts/sidecar-mirror.mjs',
  'media-downloader': '../media-downloader/scripts/sidecar-mirror.mjs',
}

function releaseUrl(tag, asset) {
  return `https://github.com/${REPO_SLUG}/releases/download/${tag}/${encodeURIComponent(asset)}`
}

function render(consumer, manifest) {
  const entries = manifest.artifacts
    .filter((entry) => entry.consumers?.includes(consumer))
    .sort((a, b) => a.platform.localeCompare(b.platform) || a.id.localeCompare(b.id))

  const byPlatform = new Map()
  for (const entry of entries) {
    if (!byPlatform.has(entry.platform)) byPlatform.set(entry.platform, [])
    byPlatform.get(entry.platform).push(entry)
  }

  const body = [...byPlatform]
    .map(([platform, list]) => {
      const tools = list
        .map(
          (entry) =>
            `    '${entry.id}': {\n` +
            `      url: '${releaseUrl(manifest.tag, entry.asset)}',\n` +
            `      sha256: '${entry.sha256}',\n` +
            `      version: '${entry.version}',\n` +
            `      license: '${entry.license}',\n` +
            `    },`,
        )
        .join('\n')
      return `  '${platform}': {\n${tools}\n  },`
    })
    .join('\n')

  return `// GENERATED by build-sidecars (scripts/emit-mirror.mjs) — do not edit by hand.
// Source of truth: ${REPO_SLUG} @ ${manifest.tag}
//
// A pinned, checksum-verified copy of the third-party binaries this project
// downloads. It is tried *before* the upstream providers: those are
// single-maintainer hosts serving mutable "latest" URLs, so an upstream going
// away — or silently changing what it serves — used to break every build at
// once, with nothing recording which build got which binary.
//
// The sha256 is the point. A mirror is only worth having if a substituted or
// truncated download is rejected instead of bundled into an installer that
// looks complete and does not work.
//
// Regenerate with \`node scripts/emit-mirror.mjs\` in the build-sidecars repo
// after publishing a new release.

export const MIRROR_TAG = '${manifest.tag}'

const MIRROR = {
${body}
}

/**
 * Returns \`{ url, sha256, version, license }\` for a tool on a platform, or
 * \`null\` when the mirror does not carry it — callers fall back to upstream.
 */
export function mirrorEntry(platformKey, tool) {
  return MIRROR[platformKey]?.[tool] ?? null
}
`
}

function main() {
  const flags = parseArgs(process.argv.slice(2))
  const manifest = readManifest(join(ROOT, 'manifest.json'))
  const wanted =
    flags.consumer && flags.consumer !== true ? [String(flags.consumer)] : Object.keys(CONSUMERS)

  let stale = 0
  for (const consumer of wanted) {
    const relative = CONSUMERS[consumer]
    if (!relative) {
      throw new Error(`unknown consumer "${consumer}" — known: ${Object.keys(CONSUMERS).join(', ')}`)
    }

    const target = resolve(ROOT, relative)
    const rendered = render(consumer, manifest)
    const current = existsSync(target) ? readFileSync(target, 'utf8') : null

    if (current === rendered) {
      log.info(`${consumer}: up to date`)
      continue
    }
    if (flags.check) {
      stale += 1
      log.fail(`${consumer}: ${target} is stale`)
      continue
    }
    if (!existsSync(resolve(target, '..'))) {
      log.warn(`${consumer}: ${target} — parent directory missing, skipping`)
      continue
    }
    writeFileSync(target, rendered, 'utf8')
    log.ok(`${consumer}: wrote ${target}`)
  }

  if (stale > 0) {
    throw new Error(`${stale} consumer file(s) stale — run: node scripts/emit-mirror.mjs`)
  }
}

try {
  main()
} catch (error) {
  log.fail(error.message)
  process.exit(1)
}
